# width of the wheels
wheel_width: 0.009

# radius of the wheels
wheel_radius: 0.033

# distance between the center wheels
wheel_base: 0.16

# length of the main chassis link
chassis_length: 0.138

# thickness of the plate that forms the chassis
chassis_thickness: 0.14 # 0.033

# height of wheel axle from bottom of chassis
wheel_axle_offset: 0.02

# chassis mass
chassis_mass: 1.0

# wheel mass
wheel_mass: 0.03

# Number of encoder ticks per wheel revolution, 12 bit per 360deg so 4096 ticks  per rev
encoder_ticks_per_rev: 4096

# Translational velocity in m/s (max)
tran_vel_max: 0.22

# Rotational velocity in rad/s (max)
rot_vel_max: 2.84

# Rotational Velocity of the motor in rad/s (max)
motor_rot_max: 6.35492

# Maximum motor power (command to send ints to ESC for output between +- 265)
motor_pwr_max: 265

# Maximum motor torque (stall) in Nm (9V: 1.0 | 11.1V: 1.4 | 12V: 1.5)
motor_torque_max: 1.5