# width of the wheels
wheel_width: 0.5

# radius of the wheels
wheel_radius: 0.5

# distance between the center wheels
wheel_base: 1.5

# length of the main chassis link
chassis_length: 2

# thickness of the plate that forms the chassis
chassis_thickness: 0.5