# waypoint x coords for pentagon
# waypoint_x: [3, 7, 7, 5, 3]
waypoint_x: [0, 0.5, 0.5, 0.25, 0]

# waypoint y coords for pentagon
# waypoint_y: [2, 2, 7, 10, 7]
waypoint_y: [0, 0, 0.5, 1., 0.5]

# frequency of control loop
frequency: 60.

# threshold for heading and position
threshold : 0.02

# Proportional control constant for angular veloicty
P_h: 5.

# Proportional control constant for linear velocity
P_l: 5.